spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruleengine?createDatabaseIfNotExist=true&useSSL=true
    username: user
    password: pass
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8081

logging:
  level:
    org.mvel2: trace


insurance:
  min:
    premiumAmount: 10000
    premiumYear:  5
